- name: Create output file for logs
  ansible.builtin.file:
    path: {{ OUTPUT_DIR }}
    state: touch

- name: Create OTEL collector config
  ansible.builtin.template:
    src: otel_config.j2
    dest: {{ DEST_CONFIG }}

- name: Run otel collector
  # What the following command does:
  # It runs docker container for otel collector using configuration file
  # that is created on DEST_CONFIG or in /etc/otel/collector-config.yaml
  # Since exporters in config file is listed, we do not need to specify output
  ansible.builtin.command: >
    sudo docker run
    -v {{ DEST_CONFIG }}:/collector-config.yaml
    otel/opentelemetry-collector:0.106.1
    --config collector-config.yaml