- name: Create output directory for logs
  ansible.builtin.file:
    path: "{{ OUTPUT_DIR }}"
    state: directory

- name: Create file for output
  ansible.builtin.file:
    path: "{{ OUTPUT_DIR_File }}"
    state: touch

- name: Create folder for otel configuration
  ansible.builtin.file:
    path: "{{ DEST_CONFIG_FOLDER }}"
    state: directory

- name: Setting facts for OS_SYSTEM - Fedora
  set_fact:
    OS_System: "{{ ansible_distribution }}"
  
- name: Setting facts for IPV4
  set_fact:
    OS_System_IPv4: "{{ ansible_default_ipv4.address }}"

- name: Setting facts for System Package module
  set_fact:
    OS_System_package_module: "{{ ansible_pkg_mgr }}"

- name: Create OTEL collector config
  ansible.builtin.template:
    src: otel_config.j2
    dest: "{{ DEST_CONFIG_File }}"

#- name: Run otel collector
  # What the following command does:
  # It runs docker container for otel collector using configuration file
  # that is created on DEST_CONFIG or in /etc/otel/collector-config.yaml
  
  # Since exporters in config file is listed, we do not need to specify output
  #ansible.builtin.command: >
    #sudo docker run
   # -v /etc/otel/collector-config.yml:/collector-config.yaml 
    #-v /var/log/otel_folder/:/var/log/otel_folder/ 
   # otel/opentelemetry-collector:0.106.1 
    #--config /collector-config.yaml