- name: Check if output directory exists
  ansible.builtin.stat: 
    path: "{{ OUTPUT_DIR }}"
  register: backup_folder_exists

- name: Create output directory for logs
  ansible.builtin.file:
    path: "{{ OUTPUT_DIR }}"
    state: directory
  when: not backup_folder_exists.stat.exists

- name: Check if output file exists
  ansible.builtin.stat:
    path: "{{ OUTPUT_DIR_File }}"
  register: output_file_exists

- name: Create file for output data
  ansible.builtin.file:
    path: "{{ OUTPUT_DIR_File }}"
    state: touch
    mode: '0644'
  when: not output_file_exists.stat.exists

- name: Check if otel folder exists
  ansible.builtin.stat:
    path: "{{ DEST_CONFIG_FOLDER }}"
  register: otel_config_folder_exists

- name: Create folder for otel configuration
  ansible.builtin.file:
    path: "{{ DEST_CONFIG_FOLDER }}"
    state: directory
  when: not otel_config_folder_exists.stat.exists

- name: Setting facts for OS_SYSTEM - Fedora
  set_fact:
    OS_System: "{{ ansible_distribution }}"
  
- name: Setting facts for IPV4
  set_fact:
    OS_System_IPv4: "{{ ansible_default_ipv4.address }}"

- name: Setting facts for System Package module
  set_fact:
    OS_System_package_module: "{{ ansible_pkg_mgr }}"

- name: Check if Otel Configuration file exists
  stat:
    path: "{{ DEST_CONFIG_File }}"
  register: otel_config_file

- name: Create otel config file
  ansible.builtin.file:
    path: "{{ DEST_CONFIG_File }}"
    state: touch
    mode: '0644'
  when: not otel_config_file.stat.exists

- name: Deploy OTEL collector config
  ansible.builtin.template:
    src: otel_config.j2
    dest: "{{ DEST_CONFIG_File }}"

- name: Run otel collector
  # What the following command does:
  # It runs docker container for otel collector using configuration file
  # that is created on DEST_CONFIG or in /etc/otel/collector-config.yaml
  
  # Since exporters in config file is listed, we do not need to specify output
  ansible.builtin.shell: >
    sudo docker run
    -v /etc/otel/collector-config.yml:/collector-config.yaml
    -v /var/log/otel_folder/:/var/log/otel_folder/
    otel/opentelemetry-collector:0.106.1
    --config /collector-config.yaml &