
- name: Deploy test SSHD configuration file
  ansible.builtin.template:
    src: sshd_config_template.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  
- name: Deploy banner config
  ansible.builtin.template: 
    src: banner_info.j2
    dest: "{{ sshd_banner }}"
  notify: Restart sshd service
