
- name: Deploy test SSHD configuration file
  ansible.builtin.template:
    src: sshd_config_template.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Restart sshd service
